### ISSUE TITLE
History of LUT selection does not work as expected

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#129]
The name/LUT do not match when "Set LUT" is run again (always inits to Red.lut)

**Comment by skalarproduktraum** [comment]
Does @ctrueden maybe have an idea how this could be solved?

**Comment by ctrueden** [comment]
The order of relevant operations here is:

1. `SetLUT` is instantiated and context is injected.
2. The `InitPreprocessor` calls the `initialize()` method.
3. The `LoadInputsPreprocessor` loads the last-used values from persistent storage and populates them. Note that this does _not_ trigger any callbacks.
4. The input harvester dialog pops up. When values are changed in the UI, callbacks are triggered.

So the questions are:

* _Why doesn't the previous `colorTable` value restore as desired from persistent storage?_ This is very likely because `ColorTable8` does not have a constructor that takes a `String`, so there is no way to restore a persisted color table from string-based storage. We could fix this.
* _Failing restoration of the `colorTable` value, how can we programmatically assign it based on the restored value of `lutName`?_ Might work to implement `Previewable` and override the `preview()` method, although I did not test it, and it would be a bit hacky.
* _Would it be worthwhile to make some new object type for LUTs that includes both the name and associated `ColorTable` in a single widget?_ Then others who need this functionality wouldn't have to reinvent the same wheel.
