### ISSUE TITLE
Importing of large .obj files fails without a clear error message

### ISSUE THREAD

**Issue by aryaman-gupta** [scenerygraphics/sciview#160]
A Java Null Pointer Exception is thrown and shown in the logs, but a clearer error message via a pop up indicating that the file is too large (possibly with the maximum size acceptable in terms of vertices) would make it easier for the user to understand what happened. I presume the error is because of the size, because smaller files are imported correctly, but I'm not sure about this.

**Comment by aryaman-gupta** [comment]
A couple of whiles for which this error occurred:

[Archive.zip](https://github.com/scenerygraphics/sciview/files/2932643/Archive.zip)

**Comment by skalarproduktraum** [comment]
The objects are actually imported, they are just physically very large, so they were out of view. 

However, the bounding box handling in sciview uncovered an inconsistency in the Node bounding box calculation in scenery, where it would not recurse into children. This has been fixed in https://github.com/scenerygraphics/scenery/commit/1a5b1e71.
