### ISSUE TITLE
Ellipsoid shapes/meshes

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#17]
We are going to need to be able to render ellipsoid shapes

**Comment by skalarproduktraum** [comment]
You can use scenery.Sphere for that and modify the Node.scale vector to create ellipsoids for the moment. Is this sufficient or would you like something more sophisticated?

I was considering adding superellipses because they could be very useful for defining 3D ROIs in Drosophila or Tribolium, e.g.

**Comment by kephale** [comment]
http://forum.imagej.net/t/surface-projections-3d-2d/11724

**Comment by kephale** [comment]
@alessandrofelder
