### ISSUE TITLE
Compass

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/sciview#277]
What compass are folks most interested in?

I like BigDataViewer's minimap ![example screenshot of minimap](https://imagej.net/_images/d/de/Bdv-overlays-1.png)  
Figure from https://imagej.net/BigDataViewer

@xulman sent https://github.com/scenerygraphics/sciview/pull/276 which has proven to be useful for debugging, and we don't have a proper compass yet. It is lightweight, which is nice.

**Comment by kephale** [comment]
![image](https://user-images.githubusercontent.com/400105/88381092-b764ef80-cd73-11ea-9470-4ebceab3e494.png)
This is from https://github.com/scenerygraphics/sciview/pull/276, and is positioned/aligned in world space.

**Comment by kephale** [comment]
I started this branch https://github.com/scenerygraphics/sciview/tree/compass based on https://github.com/scenerygraphics/sciview/pull/276

This is the current version. There are a few annoyances, but it is probably useful enough to merge sooner than later.

![compass_demo_001](https://user-images.githubusercontent.com/400105/88389576-bc7e6a80-cd84-11ea-936d-ed4b3a6f6d17.gif)

**Comment by kephale** [comment]
2 things that could make this better:
- if you move the Camera quickly, then the compass can be briefly left behind. 
- The compass is an element of the scene, so it can go behind things. This might not always be desirable, an always-on-top mode would be nice.

**Comment by kephale** [comment]
Fixed
![compass_demo_002](https://user-images.githubusercontent.com/400105/88394743-f011c280-cd8d-11ea-960f-e3bbb5336dbd.gif)

**Comment by xulman** [comment]
I think we should have both (in menu or in some "view settings panel" a toggle (radio buttons) to disable/enableAxes/enableBDV):

The 3-axes is:
- lightweight: only three, bold, axes-color-coded (not font renderings) cylinders -> a few triangles
- visible better because it is rather bold, thick
- shows clearly the positive direction of the world axes
- I find it useful for developers, I often confused axes at my beginnings and wanted to see if my programmed rotation (for example) is rotating the expected way, along the right axis (*)
- I would love to keep control of the axes from the Inspector (and could position it "on" my data..., disable visibility of some axis or make one axis longer -- I use these features from time to time)

The BDV is:
- well-known, "our ppl" are used to it
- looks much better -> important feature for screen shots for papers
- shows nicely (better than 3-axes) how is the world positioned now,
- I find it useful for users: it is easier for tracking the side you are looking at now when that is hard to track by just looking at the screen content (also if one is used to look at his volumetric data in BDV...and knows her favorite views...)

I know that BDV can replace 3-axes. Still I find reading out axes from 3-axes better than from BDV's frame box.

Only my two cents...
Vlado

----------------
(*) Note the differences in axes in computer graphics (y is not in "Earth's ground plane" (lateral), and heads up on the screen) and image processing (y-is lateral, z (z slices) is what goes "up", y heads down on the screen)

**Comment by xulman** [comment]
I really like that compass in the top-left corner, very nice!
(I have to look into the code how you achieved that)
