### ISSUE TITLE
Debug messages are printed to `System.out`

### ISSUE THREAD

**Issue by rimadoma** [scenerygraphics/SciView#56]
Debug messages should be printed using `LogService.debug(String)` instead of `System.out.println(String)` so that they can be hidden.

**Comment by skalarproduktraum** [comment]
Hey @rimadoma,

so I'm using slf4j for that at the moment, not directly System.out/err.println(). I'll investigate how both could be coupled. Does the LogService support string interpolation as slf4j does? (Maybe @ctrueden knows?) I'm asking because slf4j has this very nice optional string interpolation which only gets executed in case you are actually using this log level, which is very useful for debug and trace logging.

**Comment by rimadoma** [comment]
@skalarproduktraum at least you can set logging level, and it's also an option the user can set. Messages below the level are not shown.

**Comment by ctrueden** [comment]
Logging in SciJava is explained here: https://imagej.net/Logging

The `scijava-log-slf4j` pipes all SciJava log output _into_ SLF4J, so you can feed SciJava logging into the logging framework of your choice via SLF4J that way.

The SciJava logging framework itself does _not_ support string interpolation.

I think Scenery sticking with SLF4J is probably just fine—no need to switch everything. However, I think the `System.out.println` calls to which @rimadoma refers are here in SciView—try `git grep System.out` to see them. Since SciView is already built on SciJava, make it makes sense for SciView to use the SJC LogService?

**Comment by skalarproduktraum** [comment]
Okay, it's helpful to read issues fully, I was under the impression this was filed with scenery xD

For SciView, it should be fine to use the logging service.

**Comment by kephale** [comment]
Done
