### ISSUE TITLE
Issues with scenery 0.2.4-SNAPSHOT

### ISSUE THREAD

**Issue by kephale** [scenerygraphics/SciView#63]
I am confirming (https://github.com/bonej-org/BoneJ2/issues/86) the OpenGL black screen with the 0.2.4-SNAPSHOT of scenery when running basic tests from SciView.

The Vulkan failure to compile also exists (with enforcer on).

When the enforcer is skipped, Vulkan renders (no black screen like in OpenGL). However, when toggling to VR this error comes up: https://github.com/scenerygraphics/scenery/issues/135

**Comment by skalarproduktraum** [comment]
Hi @kephale,

the black screen issue you are describing is a problem I introduced by accident with scenerygraphics/scenery#132. It was fixed in scenery/4d956ed34ba2c32cfc60b44fcdb40b4938a54759.

Could you please elaborate on the enforcer issue? Is this related to JDK9-based builds from lwjgl? If yes, this can be relieved by adding 
```
<configuration>
                    <rules>
                        <banDuplicateClasses>
                            <ignoreClasses>
                                <ignoreClass>module-info</ignoreClass>
                            </ignoreClasses>
                        </banDuplicateClasses>
                        <enforceBytecodeVersion>
                            <maxJdkVersion>1.9</maxJdkVersion>
                        </enforceBytecodeVersion>
                    </rules>
                </configuration>
```
to enforcer configuration in the pom. As this is config inherited from scijava-common, maybe @ctrueden could let us know whether lifting the restriction to JDK8 bytecode would be something feasible 👍 

On a related not, for production builds, please don't use the SNAPSHOT versions, they are all WIP and only meant for testing.
